---

- name: Download rancher
  get_url:
    url: https://github.com/rancher/convoy/releases/download/v0.5.0-rc1/convoy.tar.gz
    dest: /tmp
    mode: 0444
  tags:
    - rancher

- name: Unpack rancher 
  command: tar -xzvf /tmp/convoy.tar.gz -C /usr/bin --strip 1
  tags:
    - rancher
  become: true  

- name: Delete rancher download
  command: rm /tmp/convoy.tar.gz
  tags:
    - rancher

- name: Add rancher as docker plugin
  command: bash -c 'echo "unix:///var/run/convoy/convoy.sock" > /etc/docker/plugins/convoy.spec'
  become: true
  tags:
    - rancher

- name: Copy convoy daemon start script
  copy:
    src: ./../files/convoy-start.sh
    dest: /usr/local/bin
    mode: 0744
  tags:
    - rancher
  become: true

- name: Copy convoy daemon service
  copy:
    src: ./../files/convoy.service
    dest: /etc/systemd/system
    mode: 0644
  tags:
    - rancher
  become: true

- name: Start convoy dameon
  command: systemctl daemon-reload
  tags:
    - rancher
  become: true

- name: Ensure the Docker service is running (CentOS)
  service:
    name=convoy.service
    state=started
    enabled=yes
  when: os.centos
  tags:
    - rancher
  become: true

