---

- name: Create Volume Group
  lvg:
    vg: vg_gluster
    pvs: "{{ device }}"
    state: present
  tags:
    - create-logicalvolume
  become: true

- name: Create Logical Volume
  lvol:
    vg: vg_gluster
    lv: bricks
    size: "{{ gluster_size }}"
  tags:
    - create-logicalvolume
  become: true

- name: Formatting filesystem with XFS
  filesystem:
    fstype: xfs
    dev: /dev/vg_gluster/bricks
  tags:
    - create-logicalvolume
  become: true

- name: Creates bricks directory
  file: 
    path: /bricks
    state: directory
  tags:
    - create-logicalvolume
  become: true

- name: Mount bricks 
  mount:
    path: /bricks
    src: /dev/vg_gluster/bricks
    fstype: xfs
    state: mounted
  tags:
    - create-logicalvolume
  become: true
